### ISSUE TITLE
Soda plugin error

### ISSUE THREAD

**Issue by jeremycopinlm** [kestra-io/plugin-soda#19]
### Actual Behaviour

Plugin fails on a Python error

**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'soda.soda_cloud'**

### Steps To Reproduce

python 3.10.6
soda + soda-core-bigquery 3.0.39

### Environment Information

- Kestra Version: 0.8.1
- Plugin: 0.8+

### Example flow

```
tasks:
- id: soda_scan
  type: io.kestra.plugin.soda.Scan
  requirements:
  - soda-core-bigquery
  - google-cloud-bigquery-storage
  - pyarrow
```
